server:
  port: 9093
spring:
    datasource:
        driver-class-name: org.h2.Driver
        platform: h2
        url: jdbc:h2:file:~/prova-cadastro-clientes
        username: sa
        password:
#        schema: classpath:/sql/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
